export enum IndexEnum {
  NEAR = 'near',
  ETHEREUM = 'eth',
  //   BTC = 'BTC',
  //   BNB = 'BNB',
  //   SOL = 'SOL',
  //   AVAX = 'AVAX',
  //   MATIC = 'MATIC',
  //   DOT = 'DOT',
  //   ADA = 'ADA',
  //   DOGE = 'DOGE',
  //   LTC = 'LTC',
  //   BCH = 'BCH',
  //   XRP = 'XRP',
  //   LINK = 'LINK',
  //   UNI = 'UNI',
  //   AAVE = 'AAVE',
  //   COMP = 'COMP',
  //   YFI = 'YFI',
  //   SUSHI = 'SUSHI',
  //   MKR = 'MKR',
  //   UMA = 'UMA',
  //   SNX = 'SNX',
  //   REN = 'REN',
  //   BAL = 'BAL',
  //   CRV = 'CRV',
  //   KNC = 'KNC',
}
