export enum MovementTypeEnum {
  LOGIN = 'LOGIN',
  TRANSFER = 'TRANSFER',
  SWAP = 'SWAP',
  BRIDGE = 'BRIDGE',
  WITHDRAWAL = 'WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
}
